### ISSUE TITLE
v3 considerations

### ISSUE THREAD

**Issue by betamos** [libp2p/zeroconf#24]
Just a brain dump of a couple of things that could be worth looking into before churning out a next version:

- If breaking changes are ok, the API could be more Go-idiomatic:
  - Accept a context in all long-running functions. Currently, the server has to be manually shut down.
  - Config options could perhaps be structs instead of currently function-that-modifies-private-struct.
- There's [a serious Windows bug in some mdns implementations in Go](https://github.com/grandcat/zeroconf/pull/81) preventing sending/broadcasting properly. I'm not positive this project is affected but I've been meaning to look into it. It'd be a nice upgrade incentive if so.

If any of these are worthy to pursue, we can break into separate issues. Happy to contribute.

**Comment by marten-seemann** [comment]
@betamos, thank you for your input here. I'm definitely opposed to cutting another major here, and collecting a list of changes we want to go into that release is the right way to approach this.

I'd like add to the list:
* remove all constructor options that have default values. Use an option for them instead.
* add an error return value to options

> * Config options could perhaps be structs instead of currently function-that-modifies-private-struct.

Actually, I'd consider the option pattern quite idiomatic. See https://www.sohamkamani.com/golang/options-pattern/ for example. We use it all over libp2p.

> * Accept a context in all long-running functions. Currently, the server has to be manually shut down.

I'm not a fan of using contexts for shutdowns. The reason is that it's inherently racy: You cancel the context, and then _eventually_ the service shuts down, and you have no way of knowing when that has happened and you can safely reuse resources.

---
> There's https://github.com/grandcat/zeroconf/pull/81 preventing sending/broadcasting properly. I'm not positive this project is affected but I've been meaning to look into it. It'd be a nice upgrade incentive if so.

Given that this is a fork of `grandcat/zeroconf`, we're probably affected. We forked because we had trouble getting our fixes merged into upstream, which seems to be the problem with https://github.com/grandcat/zeroconf/pull/81.
Any help with this would be appreciated! I don't have a Windows setup, so this would be very hard for me to investigate.

This is independent from a v3 of this library, isn't it? There's no API change.

**Comment by betamos** [comment]
> Actually, I'd consider the option pattern quite idiomatic. [...] We use it all over libp2p.

Then by all means, keep it :) I thought it was a leftover from the parent project -- hadn't seen this elsewhere. It reminds me of the builder pattern which is quite common in e.g. Rust.

> I'm not a fan of using contexts for shutdowns. The reason is that it's inherently racy: You cancel the context, and then eventually the service shuts down, and you have no way of knowing when that has happened and you can safely reuse resources.

Contexts can still be used together with clean shutdown though? You can use context for the cancellation, and then await completion in another goroutine. That could mean either awaiting a channel closure, a dedicated `Wait()` method or an iterator-like method such as `listener.Accept() (*Conn, error)`. I use this pattern in my project for anything that is, let's say, "async enough" to need its own goroutine.

For my use-case, I am happy either way since I use `Register` and `Browse` in conjunction, which lets me use a `defer server.Shutdown()`.

> Any help with this would be appreciated! I don't have a Windows setup, so this would be very hard for me to investigate.
> This is independent from a v3 of this library, isn't it? There's no API change.

Correct, there's no API change. I can check on my Windows setup.

**Comment by betamos** [comment]
Btw, that Windows issue was a red herring. I spent a day debugging and it turned out there was an issue with my NIC driver for windows, that somehow stopped receiving multicast dns traffic after some amount of time.

Both sending and receiving works just fine for me on a different NIC. This was on a recent build of Windows 10.

**Comment by BigLep** [comment]
We're going to close this issue because we don't believe the API changes are the direction we want to go.   Thank you for investigating the Windows issue.

**Comment by cpuchip** [comment]
I've tested this version of ZeroConf on windows and yes it does work for locally hosted services running on the same machine it cannot see services advertised on the network at large. applying [davidflowerday](https://github.com/davidflowerday) fix here : https://github.com/grandcat/zeroconf/pull/81 does work on the client side but a similar fix is needed on the service side to actually respond to requests in a multicast way on windows.

**Comment by marten-seemann** [comment]
@cpuchip Can you please open a new issue (or even better, a PR), if you think there's still a problem here?
